#!/bin/sh
# Generate the help tags files for all plugins

set -Ceu

echo 'Ignore plugin/**/*.vim and permission errors for /usr and /var below:' >&2

# http://vim.wikia.com/wiki/Vim_as_a_system_interpreter_for_vimscript
exec vim -i NONE -V1 -nNesXc 'packloadall | helptags ALL' -c 'echo "" | qall!'
